from bottle import Bottle, request, redirect, template, static_file, response
from beaker.middleware import SessionMiddleware
from oauth2client.client import flow_from_clientsecrets
from googleapiclient.discovery import build
from urllib.parse import urlparse
import httplib2
import sqlite3
import os
import json
import re

APP = Bottle()

# --------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------

# Google OAuth (must match your Google Cloud OAuth client)
REDIRECT_URI   = 'http://localhost:8080/redirect'   # HTTP for local dev only
CLIENT_SECRETS = 'client_secret.json'               # downloaded JSON
DB_PATH        = 'history.db'                       # per-user search history

# Shared search database generated by crawler + indexer
SEARCH_DB_PATH = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "frontend", "search.db")
)

PAGE_SIZE = 10   # number of results per page


# --------------------------------------------------------------------
# Per-user history (keep at most 10 recent queries)
# --------------------------------------------------------------------

def init_db() -> None:
    """Ensure the local history database and table exist."""
    with sqlite3.connect(DB_PATH) as con:
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS history (
              user_id TEXT,
              query   TEXT,
              ts      DATETIME DEFAULT CURRENT_TIMESTAMP
            )
            """
        )


def add_query(user_id: str, q: str) -> None:
    """
    Record one query for this user and trim to the 10 most recent
    (by timestamp).
    """
    if not (user_id and q):
        return

    with sqlite3.connect(DB_PATH) as con:
        con.execute(
            "INSERT INTO history(user_id, query) VALUES (?, ?)",
            (user_id, q),
        )
        # Keep only the newest 10 rows for this user
        con.execute(
            """
            DELETE FROM history
            WHERE user_id = ?
              AND rowid NOT IN (
                SELECT rowid
                FROM history
                WHERE user_id = ?
                ORDER BY ts DESC
              )
            """,
            (user_id, user_id),
        )


def recent_queries(user_id: str) -> list[str]:
    """
    Return up to 10 most-recent UNIQUE queries for this user,
    ordered from newest to oldest.
    """
    if not user_id:
        return []

    with sqlite3.connect(DB_PATH) as con:
        cur = con.execute(
            """
            SELECT query
            FROM (
                SELECT query, MAX(ts) AS last_ts
                FROM history
                WHERE user_id = ?
                GROUP BY query
            )
            ORDER BY last_ts DESC
            LIMIT 10
            """,
            (user_id,),
        )
        return [row[0] for row in cur.fetchall()]


def global_suggestions(prefix: str, limit: int = 10) -> list[str]:
    """
    Suggest up to `limit` terms from the global Lexicon table
    (used for autocomplete when user is not logged in).
    """
    prefix = prefix.strip().lower()
    if not prefix:
        return []

    with sqlite3.connect(SEARCH_DB_PATH) as con:
        cur = con.execute(
            """
            SELECT word
            FROM Lexicon
            WHERE lower(word) LIKE ?
            ORDER BY word
            LIMIT ?
            """,
            (prefix + "%", limit),
        )
        return [row[0] for row in cur.fetchall()]


# --------------------------------------------------------------------
# Search core (multi-word query support)
# --------------------------------------------------------------------

def looks_like_url(text: str) -> bool:
    """Heuristic to decide if a string is actually just a URL."""
    if not text:
        return False
    t = text.strip().lower()
    return (
        t.startswith("http://")
        or t.startswith("https://")
        or "://" in t
        or "www." in t
    )


def run_query(q: str) -> list[dict]:
    """
    Execute a multi-word search over the indexed corpus.

    - Split the query into tokens.
    - Look up each token in the Lexicon to get word_ids.
    - Find all documents containing any of those word_ids.
    - Rank documents by:
        (1) how many distinct query words they match (match_count),
        (2) PageRank score (score).
    - Build a list of result dictionaries for the template.
    """
    if not q:
        return []

    # Example: "ece326 lab3 tutorial" -> ["ece326", "lab3", "tutorial"]
    tokens = re.findall(r"\w+", q.lower())
    if not tokens:
        return []

    con = sqlite3.connect(SEARCH_DB_PATH)
    cur = con.cursor()

    # 1) Map query tokens to word_ids via Lexicon
    placeholders = ",".join("?" for _ in tokens)
    cur.execute(
        f"SELECT word_id FROM Lexicon WHERE lower(word) IN ({placeholders})",
        tokens,
    )
    rows = cur.fetchall()
    if not rows:
        con.close()
        return []

    word_ids = [r[0] for r in rows]

    # 2) For all matching word_ids, find docs and count how many
    #    distinct query words each doc contains.
    placeholders = ",".join("?" for _ in word_ids)
    cur.execute(
        f"""
        SELECT doc_id, COUNT(DISTINCT word_id) AS match_count
        FROM InvertedIndex
        WHERE word_id IN ({placeholders})
        GROUP BY doc_id
        """,
        word_ids,
    )
    doc_rows = cur.fetchall()
    if not doc_rows:
        con.close()
        return []

    doc_ids = [r[0] for r in doc_rows]

    # 3) Join Documents + PageRank with the match_count table and sort
    placeholders = ",".join("?" for _ in doc_ids)
    cur.execute(
        f"""
        SELECT d.url, d.title, d.description, p.score, m.match_count
        FROM (
            SELECT doc_id, COUNT(DISTINCT word_id) AS match_count
            FROM InvertedIndex
            WHERE word_id IN ({",".join("?" for _ in word_ids)})
            GROUP BY doc_id
        ) AS m
        JOIN Documents AS d ON d.doc_id = m.doc_id
        JOIN PageRank  AS p ON p.doc_id = m.doc_id
        WHERE d.doc_id IN ({placeholders})
        ORDER BY m.match_count DESC, p.score DESC
        """,
        (*word_ids, *doc_ids),
    )
    rows = cur.fetchall()
    con.close()

    results: list[dict] = []
    for (url, title, desc, score, match_count) in rows:
        parsed = urlparse(url)
        host = parsed.netloc

        # If title is missing or looks like a URL, replace with a generic label.
        if not title or looks_like_url(title) or title.strip() == url.strip():
            if url.lower().endswith(".pdf"):
                title = "PDF"
            else:
                title = "Page"

        # Build a short snippet from description
        desc = desc or ""
        snippet = desc.replace("\n", " ").strip()
        if url in snippet:
            snippet = snippet.replace(url, "").strip()
        if len(snippet) > 200:
            snippet = snippet[:197].rstrip() + "..."

        # Build a short display URL (hostname + first 1–2 segments of path)
        path = parsed.path or ""
        segments = [s for s in path.split("/") if s]
        if segments:
            if len(segments) > 2:
                short_path = "/".join(segments[:2]) + "/..."
            else:
                short_path = "/".join(segments)
            display_url = host + "/" + short_path
        else:
            display_url = host

        results.append(
            {
                "url": url,
                "title": title,
                "display_url": display_url,
                "snippet": snippet,
                "pagerank": float(score),
                "match_count": int(match_count),
            }
        )

    return results


# --------------------------------------------------------------------
# Routes
# --------------------------------------------------------------------

@APP.get("/")
def home():
    """
    Home page.
    - If signed in, show user email and recent searches.
    - If anonymous, show basic search box.
    """
    s = request.environ["beaker.session"]
    email = s.get("email")
    qs = recent_queries(s.get("sub"))
    return template("home", email=email, qs=qs)


@APP.route("/search", method=["GET", "POST"])
def do_search():
    """
    Handle search requests:
    - POST: new query from search box.
    - GET: follow-up requests for pagination.
    """
    s = request.environ["beaker.session"]

    if request.method == "POST":
        raw_q = request.forms.get("q", "").strip()
        page = 1
    else:
        raw_q = request.query.get("q", "").strip()
        try:
            page = int(request.query.get("page", "1") or 1)
        except ValueError:
            page = 1

    if page < 1:
        page = 1

    term = raw_q

    # Record history only for signed-in users and only on the first page
    if s.get("sub") and raw_q and page == 1:
        add_query(s["sub"], raw_q)

    all_results = run_query(term) if term else []

    total = len(all_results)
    total_pages = (total + PAGE_SIZE - 1) // PAGE_SIZE  # ceil division

    if page > total_pages and total_pages > 0:
        page = total_pages

    start = (page - 1) * PAGE_SIZE
    end = start + PAGE_SIZE
    results = all_results[start:end]

    has_next = page < total_pages
    has_prev = page > 1
    pages = list(range(1, total_pages + 1))

    return template(
        "results",
        email=s.get("email"),
        q=term,
        results=results,
        page=page,
        has_next=has_next,
        has_prev=has_prev,
        pages=pages,
        total_pages=total_pages,
    )


@APP.get("/login")
def login():
    """Kick off Google OAuth by redirecting to the consent page."""
    flow = flow_from_clientsecrets(
        CLIENT_SECRETS,
        scope=["profile", "email"],
        redirect_uri=REDIRECT_URI,
    )
    url = flow.step1_get_authorize_url()
    return redirect(url)


@APP.get("/redirect")
def oauth_redirect():
    """
    OAuth callback:
    - Exchange ?code for credentials.
    - Fetch user info.
    - Store email + stable user id ('sub') in session.
    """
    code = request.query.get("code")
    if not code:
        return redirect("/")

    # Exchange 'code' -> credentials (access token + id_token)
    flow = flow_from_clientsecrets(
        CLIENT_SECRETS,
        scope=["profile", "email"],
        redirect_uri=REDIRECT_URI,
    )
    creds = flow.step2_exchange(code)

    # Build authorized client and call Google UserInfo API
    http = httplib2.Http()
    authed = creds.authorize(http)
    users = build("oauth2", "v2", http=authed)
    info = users.userinfo().get().execute()

    s = request.environ["beaker.session"]
    s["email"] = info.get("email")
    s["sub"] = creds.id_token.get("sub") or info.get("id")
    s.save()
    return redirect("/")


@APP.post("/logout")
def logout():
    """Local sign-out: clear the session and return to home."""
    s = request.environ["beaker.session"]
    s.delete()
    return redirect("/")


@APP.get("/static/<path:path>")
def static(path: str):
    """Serve CSS/images during development."""
    return static_file(path, root="./static")


@APP.get("/suggest")
def suggest():
    """
    Autocomplete / search suggestion endpoint.

    - Uses both per-user history and the global Lexicon.
    - Supports multi-word completion by only completing the last token.
    """
    s = request.environ.get("beaker.session")
    user_id = s.get("sub") if s else None
    raw_q = request.query.get("q", "")
    q = raw_q.strip()

    response.content_type = "application/json"
    if not q:
        return json.dumps([])

    # Identify the last token to complete; keep the prefix as-is.
    tokens = q.split()
    last_token = tokens[-1].lower()
    base_prefix = " ".join(tokens[:-1])  # may be empty

    suggestions: list[str] = []
    seen: set[str] = set()
    MAX_TOTAL = 10

    def add_suggestion(text: str) -> None:
        text = (text or "").strip()
        if text and text not in seen:
            suggestions.append(text)
            seen.add(text)

    # 1) Personalized history suggestions
    if user_id:
        for text in recent_queries(user_id):
            candidate = (text or "").strip()
            if not candidate:
                continue
            lc = candidate.lower()

            # Case A: full-query prefix match
            if lc.startswith(q.lower()):
                add_suggestion(candidate)
            else:
                # Case B: use words from this history query to complete last token
                parts_lc = lc.split()
                parts_orig = candidate.split()
                for i, part in enumerate(parts_lc):
                    if part.startswith(last_token):
                        if base_prefix:
                            new_q = base_prefix + " " + parts_orig[i]
                        else:
                            new_q = parts_orig[i]
                        add_suggestion(new_q)
                        break

            if len(suggestions) >= 5:  # cap personalized suggestions
                break

    # 2) Global suggestions from Lexicon based on last_token
    if len(suggestions) < MAX_TOTAL:
        remaining = MAX_TOTAL - len(suggestions)
        for word in global_suggestions(last_token, limit=remaining * 3):
            w = (word or "").strip()
            if not w or not w.lower().startswith(last_token):
                continue

            if base_prefix:
                new_q = base_prefix + " " + w
            else:
                new_q = w

            add_suggestion(new_q)
            if len(suggestions) >= MAX_TOTAL:
                break

    return json.dumps(suggestions)


@APP.error(404)
def error404(_):
    """Simple custom 404 page."""
    s = request.environ.get("beaker.session")
    email = s.get("email") if s else None
    return template("error", email=email)


@APP.error(405)
def error405(_):
    """Simple custom 405 page."""
    s = request.environ.get("beaker.session")
    email = s.get("email") if s else None
    return template("error", email=email)


# --------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------

if __name__ == "__main__":
    init_db()
    session_opts = {
        "session.type": "file",
        "session.data_dir": "./.sessions",
        "session.auto": True,
        "session.cookie_expires": True,
        "session.secure": False,  # HTTP on localhost only
    }
    app = SessionMiddleware(APP, session_opts)

    from bottle import run

    run(app=app, host="0.0.0.0", port=8080, debug=True, reloader=True)
